version: "3"

services:
  backend:
    build:
      context: .
    image: backend
    container_name: backend
    hostname: backend
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    command: > 
      sh -c "sleep infinity"
    networks:
      - shared_network

  db:
    image: postgres:10-alpine
    container_name: db
    hostname: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - shared_network


networks:
    shared_network:
        driver: bridge